### ISSUE TITLE
Contact info

### ISSUE THREAD

**Issue by matthewbdubs** [wmacevoy/brainwallet#7]
Hi all,

If everyone could comment their contact info so we can discuss the details of implementations/documentation etc. That would be great.

Nowadays I tend to use Signal but am open to email, slack (I'll have to make one), etc.

__EDIT__: removed private info

**Comment by matthewbdubs** [comment]
Thanks!

**Comment by wmacevoy** [comment]
Signal vs discord anyone?

**Comment by lawalgren** [comment]
We have a discord server. I'll drop you an invite through that.
